import { ConflictException, Injectable, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import { AuthProvider, Role } from '@prisma/client';
import { createHmac, randomBytes } from 'crypto';
import { OAuth2Client } from 'google-auth-library';
import ms from 'ms';
import { GuideProfilesService } from '../guide-profiles/guide-profiles.service';
import { PrismaService } from '../prisma/prisma.service';
import { ProfilesService } from '../profiles/profiles.service';
import { UsersService } from '../users/users.service';
import { verifyAppleIdentityToken } from './apple-identity';
import { GoogleProfile } from './strategies/google.strategy';

interface TokenPair {
  accessToken: string;
  refreshToken: string;
}

export interface TokenPairWithUser extends TokenPair {
  user: TokenSubject;
}

export type TokenSubject = { id: string; email: string; username: string; usernameIsAutoGenerated: boolean; role: Role };

@Injectable()
export class AuthService {
  private readonly googleOAuthClient = new OAuth2Client();

  constructor(
    private readonly usersService: UsersService,
    private readonly profilesService: ProfilesService,
    private readonly guideProfilesService: GuideProfilesService,
    private readonly prisma: PrismaService,
    private readonly jwtService: JwtService,
    private readonly configService: ConfigService,
  ) {}

  // The native Google Sign-In SDKs mint an ID token audienced to their own
  // OAuth client (iOS/Android), distinct from GOOGLE_CLIENT_ID (the web
  // client the browser flow uses) - all three are accepted so verification
  // doesn't care which platform the client came from.
  private get mobileGoogleAudiences(): string[] {
    return [
      this.configService.get<string>('GOOGLE_CLIENT_ID')!,
      this.configService.get<string>('GOOGLE_IOS_CLIENT_ID'),
      this.configService.get<string>('GOOGLE_ANDROID_CLIENT_ID'),
    ].filter((id): id is string => Boolean(id));
  }

  private get adminEmails(): string[] {
    return (this.configService.get<string>('ADMIN_EMAILS') ?? '')
      .split(',')
      .map((email) => email.trim().toLowerCase())
      .filter(Boolean);
  }

  async handleGoogleLogin(profile: GoogleProfile): Promise<TokenPair> {
    const user = await this.loginWithIdentity({
      provider: AuthProvider.GOOGLE,
      providerId: profile.googleId,
      email: profile.email,
      emailVerified: profile.emailVerified,
      name: profile.name,
      avatarUrl: profile.avatarUrl,
    });
    return this.issueTokenPair(user);
  }

  // POST /auth/google/mobile - JSON login for apps/mobile (MOBILE_PLAN.md
  // Phase 0), which has no browser to bounce through Google's consent
  // screen. Verifies the native SDK's ID token server-side rather than
  // trusting whatever the client claims about itself.
  async handleGoogleMobileLogin(idToken: string): Promise<TokenPairWithUser> {
    // verifyIdToken throws a bare Error (not a Nest exception) for a
    // malformed/expired/wrong-audience token - without this catch it
    // surfaces as a raw 500 with the library's internal message.
    const ticket = await this.googleOAuthClient
      .verifyIdToken({ idToken, audience: this.mobileGoogleAudiences })
      .catch(() => {
        throw new UnauthorizedException('Invalid Google token');
      });
    const payload = ticket.getPayload();
    if (!payload?.email) {
      throw new UnauthorizedException('Google token has no email');
    }

    const user = await this.loginWithIdentity({
      provider: AuthProvider.GOOGLE,
      providerId: payload.sub,
      email: payload.email,
      emailVerified: payload.email_verified ?? false,
      name: payload.name,
      avatarUrl: payload.picture,
    });

    const tokens = await this.issueTokenPair(user);
    return { ...tokens, user };
  }

  private get appleBundleId(): string {
    const bundleId = this.configService.get<string>('APPLE_BUNDLE_ID');
    if (!bundleId) {
      throw new UnauthorizedException('Apple sign-in is not configured');
    }
    return bundleId;
  }

  // POST /auth/apple/mobile - Sign in with Apple (MOBILE_PLAN.md Phase 7,
  // App Store Guideline 4.8). No browser-redirect flow exists for Apple the
  // way Google has one, since this is only required for the iOS app; the
  // native AuthenticationServices sheet hands the identity token straight
  // to this endpoint. Same loginWithIdentity resolution as Google, so
  // account auto-linking on a provider-verified email applies here too -
  // though real-email Apple sign-ins are the exception, not the rule, see
  // linkAppleIdentity below for the private-relay case.
  async handleAppleMobileLogin(identityToken: string, fullName?: string): Promise<TokenPairWithUser> {
    const profile = await verifyAppleIdentityToken(identityToken, this.appleBundleId);

    const user = await this.loginWithIdentity({
      provider: AuthProvider.APPLE,
      providerId: profile.appleId,
      email: profile.email,
      emailVerified: profile.emailVerified,
      name: fullName,
    });

    const tokens = await this.issueTokenPair(user);
    return { ...tokens, user };
  }

  // POST /auth/link/apple - an Apple private-relay email (the common case:
  // the user chose "Hide My Email") never matches the email on an existing
  // Google-created account, so resolveIdentity's auto-link-on-verified-email
  // path can't fire for it. This is the manual alternative: an already
  // signed-in user explicitly attaches Apple as a second identity on their
  // own account rather than accidentally creating a duplicate one.
  async linkAppleIdentity(userId: string, identityToken: string): Promise<void> {
    const profile = await verifyAppleIdentityToken(identityToken, this.appleBundleId);

    const existing = await this.prisma.authIdentity.findUnique({
      where: { provider_providerId: { provider: AuthProvider.APPLE, providerId: profile.appleId } },
    });
    if (existing) {
      if (existing.userId !== userId) {
        throw new ConflictException('This Apple ID is already linked to a different account');
      }
      return;
    }

    await this.prisma.authIdentity.create({
      data: { userId, provider: AuthProvider.APPLE, providerId: profile.appleId, email: profile.email },
    });
  }

  // GET /auth/identities - backs the "Connected accounts" section on
  // apps/mobile's Account tab, so it can render "Link Apple ID" vs. "Apple
  // ID linked" instead of guessing from session-only state.
  async listIdentities(userId: string): Promise<AuthProvider[]> {
    const identities = await this.prisma.authIdentity.findMany({
      where: { userId },
      select: { provider: true },
    });
    return identities.map((i) => i.provider);
  }

  // Shared by the browser OAuth callback and the JSON mobile login endpoint
  // (MOBILE_PLAN.md Phase 0) - the one place that resolves a third-party
  // identity to a User, so there's exactly one place that creates users.
  async loginWithIdentity(input: {
    provider: AuthProvider;
    providerId: string;
    email: string;
    emailVerified: boolean;
    name?: string;
    avatarUrl?: string;
  }) {
    const roleOnCreate = this.adminEmails.includes(input.email.toLowerCase())
      ? Role.ADMIN
      : Role.USER;

    return this.prisma.$transaction(async (tx) => {
      const user = await this.usersService.resolveIdentity(
        {
          provider: input.provider,
          providerId: input.providerId,
          email: input.email,
          emailVerified: input.emailVerified,
          roleOnCreate,
          // Provider's display name if we have one, else the email
          // local-part - sanitizeUsernameSeed() reduces either down to the
          // username charset.
          usernameSeed: input.name ?? input.email.split('@')[0],
        },
        tx,
      );

      await this.profilesService.upsertForUser(
        user.id,
        { name: input.name, avatarUrl: input.avatarUrl },
        tx,
      );

      // MILESTONE_3.md §2.2: GuideProfile is universal now - every user
      // gets one alongside Profile, not just users who opt into guiding.
      await this.guideProfilesService.ensureForUser(user.id, tx);

      return user;
    });
  }

  async refresh(rawRefreshToken: string): Promise<TokenPair> {
    const tokenHash = this.hashRefreshToken(rawRefreshToken);
    const existing = await this.prisma.refreshToken.findUnique({
      where: { tokenHash },
      include: { user: true },
    });

    if (!existing || existing.revokedAt || existing.expiresAt < new Date()) {
      throw new UnauthorizedException('Invalid refresh token');
    }

    await this.prisma.refreshToken.update({
      where: { id: existing.id },
      data: { revokedAt: new Date() },
    });

    return this.issueTokenPair(existing.user);
  }

  async logout(rawRefreshToken: string): Promise<void> {
    const tokenHash = this.hashRefreshToken(rawRefreshToken);
    await this.prisma.refreshToken.deleteMany({ where: { tokenHash } });
  }

  private async issueTokenPair(user: TokenSubject): Promise<TokenPair> {
    const accessToken = this.jwtService.sign(
      {
        sub: user.id,
        email: user.email,
        username: user.username,
        usernameIsAutoGenerated: user.usernameIsAutoGenerated,
        role: user.role,
      },
      {
        secret: this.configService.get<string>('JWT_ACCESS_SECRET'),
        expiresIn: this.configService.get<string>('JWT_ACCESS_TTL'),
      },
    );

    const refreshToken = randomBytes(32).toString('hex');
    const refreshTtl = this.configService.get<string>('JWT_REFRESH_TTL')!;
    const expiresAt = new Date(Date.now() + ms(refreshTtl));

    await this.prisma.refreshToken.create({
      data: {
        userId: user.id,
        tokenHash: this.hashRefreshToken(refreshToken),
        expiresAt,
      },
    });

    return { accessToken, refreshToken };
  }

  private hashRefreshToken(token: string): string {
    const secret = this.configService.get<string>('JWT_REFRESH_SECRET')!;
    return createHmac('sha256', secret).update(token).digest('hex');
  }
}
