-- AlterTable: nullable first so existing rows can be backfilled before the
-- NOT NULL/UNIQUE constraints land - same two-step pattern as
-- 20260814062503_require_trip_group_description.
ALTER TABLE "users" ADD COLUMN     "username" TEXT,
ADD COLUMN     "usernameIsAutoGenerated" BOOLEAN NOT NULL DEFAULT true;

-- Backfill: derive from the email local-part, sanitized to the app's
-- username charset (lowercase letters/digits/underscore), with a short
-- id-derived suffix to guarantee uniqueness deterministically without a
-- row-numbering pass. New users past this migration get a nicer,
-- collision-checked username via UsersService.generateUniqueUsername -
-- this backfill only needs to satisfy NOT NULL/UNIQUE for pre-existing rows.
UPDATE "users"
SET "username" = regexp_replace(lower(split_part("email", '@', 1)), '[^a-z0-9_]', '_', 'g') || '_' || substr(replace("id"::text, '-', ''), 1, 6)
WHERE "username" IS NULL;

ALTER TABLE "users" ALTER COLUMN "username" SET NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");
