// Hand-written API shapes shared across clients (apps/public, apps/admin,
// and eventually apps/mobile - MOBILE_PLAN.md Phase 0 item 7). Seeded with
// the auth/sync shapes mobile needs first; migrating public/admin off their
// inline equivalents (e.g. apps/public/src/lib/auth/session.ts's
// CurrentUser) can follow opportunistically rather than as a big-bang
// refactor. Kept in sync with the API by hand - there is no codegen step.

export * from './content';

export type Role = 'ADMIN' | 'MODERATOR' | 'USER';

export type AuthProvider = 'GOOGLE' | 'APPLE';

// Matches AuthenticatedUser from apps/api/src/auth/decorators/current-user.decorator.ts
export interface CurrentUser {
  userId: string;
  email: string;
  username: string;
  usernameIsAutoGenerated: boolean;
  role: Role;
}

// Matches the User row returned inline by POST /auth/google/mobile - see
// AuthService.handleGoogleMobileLogin.
export interface AuthUser {
  id: string;
  email: string;
  username: string;
  usernameIsAutoGenerated: boolean;
  role: Role;
}

// POST /auth/google/mobile response.
export interface MobileLoginResponse {
  accessToken: string;
  refreshToken: string;
  user: AuthUser;
}

// POST /auth/refresh response (body-based variant - see auth.controller.ts).
export interface RefreshResponse {
  accessToken: string;
  refreshToken: string;
}

// GET /me/activity-tracks response item - either a full row or, for a
// soft-deleted track, a tombstone the client uses to evict its local copy.
// See TracksService.listSince.
export type ActivityTrackSyncItem = ActivityTrackFull | ActivityTrackTombstone;

export interface ActivityTrackTombstone {
  id: string;
  isActive: false;
  updatedAt: string;
}

export interface ActivityTrackFull {
  id: string;
  userId: string;
  adventurePageId: string | null;
  tripReportId: string | null;
  activityTypeId: string;
  name: string | null;
  notes: string | null;
  geometry: { type: 'LineString'; coordinates: [number, number][] };
  samples: Array<{ d: number; e?: number; t?: number }>;
  sampleCount: number;
  startedAt: string;
  finishedAt: string;
  elapsedSeconds: number;
  movingSeconds: number | null;
  distanceMeters: number;
  ascentMeters: number | null;
  descentMeters: number | null;
  minElevationMeters: number | null;
  maxElevationMeters: number | null;
  source: 'RECORDED' | 'IMPORTED';
  visibility: 'PRIVATE' | 'PUBLIC';
  privacyTrimMeters: number | null;
  clientUuid: string | null;
  originalFileUrl: string | null;
  isActive: true;
  createdAt: string;
  updatedAt: string;
}

// GET /me/activity-tracks response envelope.
export interface ActivityTrackSyncResponse {
  data: ActivityTrackSyncItem[];
  nextCursor: string | null;
}
