/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountGuideProfileRouteImport } from './routes/account/guide-profile'
import { Route as AdventuresNewRouteImport } from './routes/adventures/new'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ClubsIndexRouteImport } from './routes/clubs/index'
import { Route as ClubsNewRouteImport } from './routes/clubs/new'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesIdRouteImport } from './routes/guides/$id'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ReviewQueueIndexRouteImport } from './routes/review-queue/index'
import { Route as TripGroupsIndexRouteImport } from './routes/trip-groups/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as AdventuresSlugIndexRouteImport } from './routes/adventures/$slug/index'
import { Route as AdventuresSlugEditRouteImport } from './routes/adventures/$slug/edit'
import { Route as ClubsClubIdIndexRouteImport } from './routes/clubs/$clubId/index'
import { Route as ClubsClubIdEditRouteImport } from './routes/clubs/$clubId/edit'
import { Route as MeActivityTracksIndexRouteImport } from './routes/me/activity-tracks/index'
import { Route as MeActivityTracksTrackIdRouteImport } from './routes/me/activity-tracks/$trackId'
import { Route as MeActivityTracksUploadRouteImport } from './routes/me/activity-tracks/upload'
import { Route as AdventuresSlugGroupsIndexRouteImport } from './routes/adventures/$slug/groups/index'
import { Route as AdventuresSlugGroupsGroupIdRouteImport } from './routes/adventures/$slug/groups/$groupId'
import { Route as AdventuresSlugGroupsNewRouteImport } from './routes/adventures/$slug/groups/new'
import { Route as AdventuresSlugHistoryIndexRouteImport } from './routes/adventures/$slug/history/index'
import { Route as AdventuresSlugHistoryVersionRouteImport } from './routes/adventures/$slug/history/$version'
import { Route as AdventuresSlugSpotsNewRouteImport } from './routes/adventures/$slug/spots/new'
import { Route as AdventuresSlugTrailsNewRouteImport } from './routes/adventures/$slug/trails/new'
import { Route as AdventuresSlugTripsTripReportIdRouteImport } from './routes/adventures/$slug/trips/$tripReportId'
import { Route as ClubsClubIdThreadsNewRouteImport } from './routes/clubs/$clubId/threads/new'
import { Route as ClubsClubIdThreadsThreadIdIndexRouteImport } from './routes/clubs/$clubId/threads/$threadId/index'
import { Route as AdventuresSlugSpotsSpotIdHistoryIndexRouteImport } from './routes/adventures/$slug/spots/$spotId/history/index'
import { Route as AdventuresSlugSpotsSpotIdHistoryVersionRouteImport } from './routes/adventures/$slug/spots/$spotId/history/$version'
import { Route as AdventuresSlugTrailsTrailIdHistoryIndexRouteImport } from './routes/adventures/$slug/trails/$trailId/history/index'
import { Route as AdventuresSlugTrailsTrailIdHistoryVersionRouteImport } from './routes/adventures/$slug/trails/$trailId/history/$version'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountGuideProfileRoute = AccountGuideProfileRouteImport.update({
  id: '/account/guide-profile',
  path: '/account/guide-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresNewRoute = AdventuresNewRouteImport.update({
  id: '/adventures/new',
  path: '/adventures/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsNewRoute = ClubsNewRouteImport.update({
  id: '/clubs/new',
  path: '/clubs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIdRoute = GuidesIdRouteImport.update({
  id: '/guides/$id',
  path: '/guides/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueIndexRoute = ReviewQueueIndexRouteImport.update({
  id: '/review-queue/',
  path: '/review-queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripGroupsIndexRoute = TripGroupsIndexRouteImport.update({
  id: '/trip-groups/',
  path: '/trip-groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugIndexRoute = AdventuresSlugIndexRouteImport.update({
  id: '/adventures/$slug/',
  path: '/adventures/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugEditRoute = AdventuresSlugEditRouteImport.update({
  id: '/adventures/$slug/edit',
  path: '/adventures/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsClubIdIndexRoute = ClubsClubIdIndexRouteImport.update({
  id: '/clubs/$clubId/',
  path: '/clubs/$clubId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsClubIdEditRoute = ClubsClubIdEditRouteImport.update({
  id: '/clubs/$clubId/edit',
  path: '/clubs/$clubId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MeActivityTracksIndexRoute = MeActivityTracksIndexRouteImport.update({
  id: '/me/activity-tracks/',
  path: '/me/activity-tracks/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeActivityTracksTrackIdRoute = MeActivityTracksTrackIdRouteImport.update({
  id: '/me/activity-tracks/$trackId',
  path: '/me/activity-tracks/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeActivityTracksUploadRoute = MeActivityTracksUploadRouteImport.update({
  id: '/me/activity-tracks/upload',
  path: '/me/activity-tracks/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugGroupsIndexRoute =
  AdventuresSlugGroupsIndexRouteImport.update({
    id: '/adventures/$slug/groups/',
    path: '/adventures/$slug/groups/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugGroupsGroupIdRoute =
  AdventuresSlugGroupsGroupIdRouteImport.update({
    id: '/adventures/$slug/groups/$groupId',
    path: '/adventures/$slug/groups/$groupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugGroupsNewRoute = AdventuresSlugGroupsNewRouteImport.update({
  id: '/adventures/$slug/groups/new',
  path: '/adventures/$slug/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugHistoryIndexRoute =
  AdventuresSlugHistoryIndexRouteImport.update({
    id: '/adventures/$slug/history/',
    path: '/adventures/$slug/history/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugHistoryVersionRoute =
  AdventuresSlugHistoryVersionRouteImport.update({
    id: '/adventures/$slug/history/$version',
    path: '/adventures/$slug/history/$version',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugSpotsNewRoute = AdventuresSlugSpotsNewRouteImport.update({
  id: '/adventures/$slug/spots/new',
  path: '/adventures/$slug/spots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugTrailsNewRoute = AdventuresSlugTrailsNewRouteImport.update({
  id: '/adventures/$slug/trails/new',
  path: '/adventures/$slug/trails/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugTripsTripReportIdRoute =
  AdventuresSlugTripsTripReportIdRouteImport.update({
    id: '/adventures/$slug/trips/$tripReportId',
    path: '/adventures/$slug/trips/$tripReportId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClubsClubIdThreadsNewRoute = ClubsClubIdThreadsNewRouteImport.update({
  id: '/clubs/$clubId/threads/new',
  path: '/clubs/$clubId/threads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsClubIdThreadsThreadIdIndexRoute =
  ClubsClubIdThreadsThreadIdIndexRouteImport.update({
    id: '/clubs/$clubId/threads/$threadId/',
    path: '/clubs/$clubId/threads/$threadId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugSpotsSpotIdHistoryIndexRoute =
  AdventuresSlugSpotsSpotIdHistoryIndexRouteImport.update({
    id: '/adventures/$slug/spots/$spotId/history/',
    path: '/adventures/$slug/spots/$spotId/history/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugSpotsSpotIdHistoryVersionRoute =
  AdventuresSlugSpotsSpotIdHistoryVersionRouteImport.update({
    id: '/adventures/$slug/spots/$spotId/history/$version',
    path: '/adventures/$slug/spots/$spotId/history/$version',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugTrailsTrailIdHistoryIndexRoute =
  AdventuresSlugTrailsTrailIdHistoryIndexRouteImport.update({
    id: '/adventures/$slug/trails/$trailId/history/',
    path: '/adventures/$slug/trails/$trailId/history/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugTrailsTrailIdHistoryVersionRoute =
  AdventuresSlugTrailsTrailIdHistoryVersionRouteImport.update({
    id: '/adventures/$slug/trails/$trailId/history/$version',
    path: '/adventures/$slug/trails/$trailId/history/$version',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/guide-profile': typeof AccountGuideProfileRoute
  '/adventures/new': typeof AdventuresNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clubs/new': typeof ClubsNewRoute
  '/guides/$id': typeof GuidesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/account/': typeof AccountIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/review-queue/': typeof ReviewQueueIndexRoute
  '/trip-groups/': typeof TripGroupsIndexRoute
  '/adventures/$slug/edit': typeof AdventuresSlugEditRoute
  '/clubs/$clubId/edit': typeof ClubsClubIdEditRoute
  '/me/activity-tracks/$trackId': typeof MeActivityTracksTrackIdRoute
  '/me/activity-tracks/upload': typeof MeActivityTracksUploadRoute
  '/adventures/$slug/': typeof AdventuresSlugIndexRoute
  '/clubs/$clubId/': typeof ClubsClubIdIndexRoute
  '/me/activity-tracks/': typeof MeActivityTracksIndexRoute
  '/adventures/$slug/groups/$groupId': typeof AdventuresSlugGroupsGroupIdRoute
  '/adventures/$slug/groups/new': typeof AdventuresSlugGroupsNewRoute
  '/adventures/$slug/history/$version': typeof AdventuresSlugHistoryVersionRoute
  '/adventures/$slug/spots/new': typeof AdventuresSlugSpotsNewRoute
  '/adventures/$slug/trails/new': typeof AdventuresSlugTrailsNewRoute
  '/adventures/$slug/trips/$tripReportId': typeof AdventuresSlugTripsTripReportIdRoute
  '/clubs/$clubId/threads/new': typeof ClubsClubIdThreadsNewRoute
  '/adventures/$slug/groups/': typeof AdventuresSlugGroupsIndexRoute
  '/adventures/$slug/history/': typeof AdventuresSlugHistoryIndexRoute
  '/clubs/$clubId/threads/$threadId/': typeof ClubsClubIdThreadsThreadIdIndexRoute
  '/adventures/$slug/spots/$spotId/history/$version': typeof AdventuresSlugSpotsSpotIdHistoryVersionRoute
  '/adventures/$slug/trails/$trailId/history/$version': typeof AdventuresSlugTrailsTrailIdHistoryVersionRoute
  '/adventures/$slug/spots/$spotId/history/': typeof AdventuresSlugSpotsSpotIdHistoryIndexRoute
  '/adventures/$slug/trails/$trailId/history/': typeof AdventuresSlugTrailsTrailIdHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/guide-profile': typeof AccountGuideProfileRoute
  '/adventures/new': typeof AdventuresNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clubs/new': typeof ClubsNewRoute
  '/guides/$id': typeof GuidesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/account': typeof AccountIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/review-queue': typeof ReviewQueueIndexRoute
  '/trip-groups': typeof TripGroupsIndexRoute
  '/adventures/$slug/edit': typeof AdventuresSlugEditRoute
  '/clubs/$clubId/edit': typeof ClubsClubIdEditRoute
  '/me/activity-tracks/$trackId': typeof MeActivityTracksTrackIdRoute
  '/me/activity-tracks/upload': typeof MeActivityTracksUploadRoute
  '/adventures/$slug': typeof AdventuresSlugIndexRoute
  '/clubs/$clubId': typeof ClubsClubIdIndexRoute
  '/me/activity-tracks': typeof MeActivityTracksIndexRoute
  '/adventures/$slug/groups/$groupId': typeof AdventuresSlugGroupsGroupIdRoute
  '/adventures/$slug/groups/new': typeof AdventuresSlugGroupsNewRoute
  '/adventures/$slug/history/$version': typeof AdventuresSlugHistoryVersionRoute
  '/adventures/$slug/spots/new': typeof AdventuresSlugSpotsNewRoute
  '/adventures/$slug/trails/new': typeof AdventuresSlugTrailsNewRoute
  '/adventures/$slug/trips/$tripReportId': typeof AdventuresSlugTripsTripReportIdRoute
  '/clubs/$clubId/threads/new': typeof ClubsClubIdThreadsNewRoute
  '/adventures/$slug/groups': typeof AdventuresSlugGroupsIndexRoute
  '/adventures/$slug/history': typeof AdventuresSlugHistoryIndexRoute
  '/clubs/$clubId/threads/$threadId': typeof ClubsClubIdThreadsThreadIdIndexRoute
  '/adventures/$slug/spots/$spotId/history/$version': typeof AdventuresSlugSpotsSpotIdHistoryVersionRoute
  '/adventures/$slug/trails/$trailId/history/$version': typeof AdventuresSlugTrailsTrailIdHistoryVersionRoute
  '/adventures/$slug/spots/$spotId/history': typeof AdventuresSlugSpotsSpotIdHistoryIndexRoute
  '/adventures/$slug/trails/$trailId/history': typeof AdventuresSlugTrailsTrailIdHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/guide-profile': typeof AccountGuideProfileRoute
  '/adventures/new': typeof AdventuresNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clubs/new': typeof ClubsNewRoute
  '/guides/$id': typeof GuidesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/account/': typeof AccountIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/review-queue/': typeof ReviewQueueIndexRoute
  '/trip-groups/': typeof TripGroupsIndexRoute
  '/adventures/$slug/edit': typeof AdventuresSlugEditRoute
  '/clubs/$clubId/edit': typeof ClubsClubIdEditRoute
  '/me/activity-tracks/$trackId': typeof MeActivityTracksTrackIdRoute
  '/me/activity-tracks/upload': typeof MeActivityTracksUploadRoute
  '/adventures/$slug/': typeof AdventuresSlugIndexRoute
  '/clubs/$clubId/': typeof ClubsClubIdIndexRoute
  '/me/activity-tracks/': typeof MeActivityTracksIndexRoute
  '/adventures/$slug/groups/$groupId': typeof AdventuresSlugGroupsGroupIdRoute
  '/adventures/$slug/groups/new': typeof AdventuresSlugGroupsNewRoute
  '/adventures/$slug/history/$version': typeof AdventuresSlugHistoryVersionRoute
  '/adventures/$slug/spots/new': typeof AdventuresSlugSpotsNewRoute
  '/adventures/$slug/trails/new': typeof AdventuresSlugTrailsNewRoute
  '/adventures/$slug/trips/$tripReportId': typeof AdventuresSlugTripsTripReportIdRoute
  '/clubs/$clubId/threads/new': typeof ClubsClubIdThreadsNewRoute
  '/adventures/$slug/groups/': typeof AdventuresSlugGroupsIndexRoute
  '/adventures/$slug/history/': typeof AdventuresSlugHistoryIndexRoute
  '/clubs/$clubId/threads/$threadId/': typeof ClubsClubIdThreadsThreadIdIndexRoute
  '/adventures/$slug/spots/$spotId/history/$version': typeof AdventuresSlugSpotsSpotIdHistoryVersionRoute
  '/adventures/$slug/trails/$trailId/history/$version': typeof AdventuresSlugTrailsTrailIdHistoryVersionRoute
  '/adventures/$slug/spots/$spotId/history/': typeof AdventuresSlugSpotsSpotIdHistoryIndexRoute
  '/adventures/$slug/trails/$trailId/history/': typeof AdventuresSlugTrailsTrailIdHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/account/guide-profile'
    | '/adventures/new'
    | '/auth/callback'
    | '/clubs/new'
    | '/guides/$id'
    | '/users/$id'
    | '/account/'
    | '/clubs/'
    | '/guides/'
    | '/reports/'
    | '/review-queue/'
    | '/trip-groups/'
    | '/adventures/$slug/edit'
    | '/clubs/$clubId/edit'
    | '/me/activity-tracks/$trackId'
    | '/me/activity-tracks/upload'
    | '/adventures/$slug/'
    | '/clubs/$clubId/'
    | '/me/activity-tracks/'
    | '/adventures/$slug/groups/$groupId'
    | '/adventures/$slug/groups/new'
    | '/adventures/$slug/history/$version'
    | '/adventures/$slug/spots/new'
    | '/adventures/$slug/trails/new'
    | '/adventures/$slug/trips/$tripReportId'
    | '/clubs/$clubId/threads/new'
    | '/adventures/$slug/groups/'
    | '/adventures/$slug/history/'
    | '/clubs/$clubId/threads/$threadId/'
    | '/adventures/$slug/spots/$spotId/history/$version'
    | '/adventures/$slug/trails/$trailId/history/$version'
    | '/adventures/$slug/spots/$spotId/history/'
    | '/adventures/$slug/trails/$trailId/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/account/guide-profile'
    | '/adventures/new'
    | '/auth/callback'
    | '/clubs/new'
    | '/guides/$id'
    | '/users/$id'
    | '/account'
    | '/clubs'
    | '/guides'
    | '/reports'
    | '/review-queue'
    | '/trip-groups'
    | '/adventures/$slug/edit'
    | '/clubs/$clubId/edit'
    | '/me/activity-tracks/$trackId'
    | '/me/activity-tracks/upload'
    | '/adventures/$slug'
    | '/clubs/$clubId'
    | '/me/activity-tracks'
    | '/adventures/$slug/groups/$groupId'
    | '/adventures/$slug/groups/new'
    | '/adventures/$slug/history/$version'
    | '/adventures/$slug/spots/new'
    | '/adventures/$slug/trails/new'
    | '/adventures/$slug/trips/$tripReportId'
    | '/clubs/$clubId/threads/new'
    | '/adventures/$slug/groups'
    | '/adventures/$slug/history'
    | '/clubs/$clubId/threads/$threadId'
    | '/adventures/$slug/spots/$spotId/history/$version'
    | '/adventures/$slug/trails/$trailId/history/$version'
    | '/adventures/$slug/spots/$spotId/history'
    | '/adventures/$slug/trails/$trailId/history'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/account/guide-profile'
    | '/adventures/new'
    | '/auth/callback'
    | '/clubs/new'
    | '/guides/$id'
    | '/users/$id'
    | '/account/'
    | '/clubs/'
    | '/guides/'
    | '/reports/'
    | '/review-queue/'
    | '/trip-groups/'
    | '/adventures/$slug/edit'
    | '/clubs/$clubId/edit'
    | '/me/activity-tracks/$trackId'
    | '/me/activity-tracks/upload'
    | '/adventures/$slug/'
    | '/clubs/$clubId/'
    | '/me/activity-tracks/'
    | '/adventures/$slug/groups/$groupId'
    | '/adventures/$slug/groups/new'
    | '/adventures/$slug/history/$version'
    | '/adventures/$slug/spots/new'
    | '/adventures/$slug/trails/new'
    | '/adventures/$slug/trips/$tripReportId'
    | '/clubs/$clubId/threads/new'
    | '/adventures/$slug/groups/'
    | '/adventures/$slug/history/'
    | '/clubs/$clubId/threads/$threadId/'
    | '/adventures/$slug/spots/$spotId/history/$version'
    | '/adventures/$slug/trails/$trailId/history/$version'
    | '/adventures/$slug/spots/$spotId/history/'
    | '/adventures/$slug/trails/$trailId/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AccountGuideProfileRoute: typeof AccountGuideProfileRoute
  AdventuresNewRoute: typeof AdventuresNewRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ClubsNewRoute: typeof ClubsNewRoute
  GuidesIdRoute: typeof GuidesIdRoute
  UsersIdRoute: typeof UsersIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ReviewQueueIndexRoute: typeof ReviewQueueIndexRoute
  TripGroupsIndexRoute: typeof TripGroupsIndexRoute
  AdventuresSlugEditRoute: typeof AdventuresSlugEditRoute
  ClubsClubIdEditRoute: typeof ClubsClubIdEditRoute
  MeActivityTracksTrackIdRoute: typeof MeActivityTracksTrackIdRoute
  MeActivityTracksUploadRoute: typeof MeActivityTracksUploadRoute
  AdventuresSlugIndexRoute: typeof AdventuresSlugIndexRoute
  ClubsClubIdIndexRoute: typeof ClubsClubIdIndexRoute
  MeActivityTracksIndexRoute: typeof MeActivityTracksIndexRoute
  AdventuresSlugGroupsGroupIdRoute: typeof AdventuresSlugGroupsGroupIdRoute
  AdventuresSlugGroupsNewRoute: typeof AdventuresSlugGroupsNewRoute
  AdventuresSlugHistoryVersionRoute: typeof AdventuresSlugHistoryVersionRoute
  AdventuresSlugSpotsNewRoute: typeof AdventuresSlugSpotsNewRoute
  AdventuresSlugTrailsNewRoute: typeof AdventuresSlugTrailsNewRoute
  AdventuresSlugTripsTripReportIdRoute: typeof AdventuresSlugTripsTripReportIdRoute
  ClubsClubIdThreadsNewRoute: typeof ClubsClubIdThreadsNewRoute
  AdventuresSlugGroupsIndexRoute: typeof AdventuresSlugGroupsIndexRoute
  AdventuresSlugHistoryIndexRoute: typeof AdventuresSlugHistoryIndexRoute
  ClubsClubIdThreadsThreadIdIndexRoute: typeof ClubsClubIdThreadsThreadIdIndexRoute
  AdventuresSlugSpotsSpotIdHistoryVersionRoute: typeof AdventuresSlugSpotsSpotIdHistoryVersionRoute
  AdventuresSlugTrailsTrailIdHistoryVersionRoute: typeof AdventuresSlugTrailsTrailIdHistoryVersionRoute
  AdventuresSlugSpotsSpotIdHistoryIndexRoute: typeof AdventuresSlugSpotsSpotIdHistoryIndexRoute
  AdventuresSlugTrailsTrailIdHistoryIndexRoute: typeof AdventuresSlugTrailsTrailIdHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/guide-profile': {
      id: '/account/guide-profile'
      path: '/account/guide-profile'
      fullPath: '/account/guide-profile'
      preLoaderRoute: typeof AccountGuideProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/new': {
      id: '/adventures/new'
      path: '/adventures/new'
      fullPath: '/adventures/new'
      preLoaderRoute: typeof AdventuresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/new': {
      id: '/clubs/new'
      path: '/clubs/new'
      fullPath: '/clubs/new'
      preLoaderRoute: typeof ClubsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$id': {
      id: '/guides/$id'
      path: '/guides/$id'
      fullPath: '/guides/$id'
      preLoaderRoute: typeof GuidesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue/': {
      id: '/review-queue/'
      path: '/review-queue'
      fullPath: '/review-queue/'
      preLoaderRoute: typeof ReviewQueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip-groups/': {
      id: '/trip-groups/'
      path: '/trip-groups'
      fullPath: '/trip-groups/'
      preLoaderRoute: typeof TripGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/': {
      id: '/adventures/$slug/'
      path: '/adventures/$slug'
      fullPath: '/adventures/$slug/'
      preLoaderRoute: typeof AdventuresSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/edit': {
      id: '/adventures/$slug/edit'
      path: '/adventures/$slug/edit'
      fullPath: '/adventures/$slug/edit'
      preLoaderRoute: typeof AdventuresSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId/': {
      id: '/clubs/$clubId/'
      path: '/clubs/$clubId'
      fullPath: '/clubs/$clubId/'
      preLoaderRoute: typeof ClubsClubIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId/edit': {
      id: '/clubs/$clubId/edit'
      path: '/clubs/$clubId/edit'
      fullPath: '/clubs/$clubId/edit'
      preLoaderRoute: typeof ClubsClubIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/activity-tracks/': {
      id: '/me/activity-tracks/'
      path: '/me/activity-tracks'
      fullPath: '/me/activity-tracks/'
      preLoaderRoute: typeof MeActivityTracksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/activity-tracks/$trackId': {
      id: '/me/activity-tracks/$trackId'
      path: '/me/activity-tracks/$trackId'
      fullPath: '/me/activity-tracks/$trackId'
      preLoaderRoute: typeof MeActivityTracksTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/activity-tracks/upload': {
      id: '/me/activity-tracks/upload'
      path: '/me/activity-tracks/upload'
      fullPath: '/me/activity-tracks/upload'
      preLoaderRoute: typeof MeActivityTracksUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/groups/': {
      id: '/adventures/$slug/groups/'
      path: '/adventures/$slug/groups'
      fullPath: '/adventures/$slug/groups/'
      preLoaderRoute: typeof AdventuresSlugGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/groups/$groupId': {
      id: '/adventures/$slug/groups/$groupId'
      path: '/adventures/$slug/groups/$groupId'
      fullPath: '/adventures/$slug/groups/$groupId'
      preLoaderRoute: typeof AdventuresSlugGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/groups/new': {
      id: '/adventures/$slug/groups/new'
      path: '/adventures/$slug/groups/new'
      fullPath: '/adventures/$slug/groups/new'
      preLoaderRoute: typeof AdventuresSlugGroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/history/': {
      id: '/adventures/$slug/history/'
      path: '/adventures/$slug/history'
      fullPath: '/adventures/$slug/history/'
      preLoaderRoute: typeof AdventuresSlugHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/history/$version': {
      id: '/adventures/$slug/history/$version'
      path: '/adventures/$slug/history/$version'
      fullPath: '/adventures/$slug/history/$version'
      preLoaderRoute: typeof AdventuresSlugHistoryVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/spots/new': {
      id: '/adventures/$slug/spots/new'
      path: '/adventures/$slug/spots/new'
      fullPath: '/adventures/$slug/spots/new'
      preLoaderRoute: typeof AdventuresSlugSpotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/trails/new': {
      id: '/adventures/$slug/trails/new'
      path: '/adventures/$slug/trails/new'
      fullPath: '/adventures/$slug/trails/new'
      preLoaderRoute: typeof AdventuresSlugTrailsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/trips/$tripReportId': {
      id: '/adventures/$slug/trips/$tripReportId'
      path: '/adventures/$slug/trips/$tripReportId'
      fullPath: '/adventures/$slug/trips/$tripReportId'
      preLoaderRoute: typeof AdventuresSlugTripsTripReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId/threads/new': {
      id: '/clubs/$clubId/threads/new'
      path: '/clubs/$clubId/threads/new'
      fullPath: '/clubs/$clubId/threads/new'
      preLoaderRoute: typeof ClubsClubIdThreadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId/threads/$threadId/': {
      id: '/clubs/$clubId/threads/$threadId/'
      path: '/clubs/$clubId/threads/$threadId'
      fullPath: '/clubs/$clubId/threads/$threadId/'
      preLoaderRoute: typeof ClubsClubIdThreadsThreadIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/spots/$spotId/history/': {
      id: '/adventures/$slug/spots/$spotId/history/'
      path: '/adventures/$slug/spots/$spotId/history'
      fullPath: '/adventures/$slug/spots/$spotId/history/'
      preLoaderRoute: typeof AdventuresSlugSpotsSpotIdHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/spots/$spotId/history/$version': {
      id: '/adventures/$slug/spots/$spotId/history/$version'
      path: '/adventures/$slug/spots/$spotId/history/$version'
      fullPath: '/adventures/$slug/spots/$spotId/history/$version'
      preLoaderRoute: typeof AdventuresSlugSpotsSpotIdHistoryVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/trails/$trailId/history/': {
      id: '/adventures/$slug/trails/$trailId/history/'
      path: '/adventures/$slug/trails/$trailId/history'
      fullPath: '/adventures/$slug/trails/$trailId/history/'
      preLoaderRoute: typeof AdventuresSlugTrailsTrailIdHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/trails/$trailId/history/$version': {
      id: '/adventures/$slug/trails/$trailId/history/$version'
      path: '/adventures/$slug/trails/$trailId/history/$version'
      fullPath: '/adventures/$slug/trails/$trailId/history/$version'
      preLoaderRoute: typeof AdventuresSlugTrailsTrailIdHistoryVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AccountGuideProfileRoute: AccountGuideProfileRoute,
  AdventuresNewRoute: AdventuresNewRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ClubsNewRoute: ClubsNewRoute,
  GuidesIdRoute: GuidesIdRoute,
  UsersIdRoute: UsersIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ReviewQueueIndexRoute: ReviewQueueIndexRoute,
  TripGroupsIndexRoute: TripGroupsIndexRoute,
  AdventuresSlugEditRoute: AdventuresSlugEditRoute,
  ClubsClubIdEditRoute: ClubsClubIdEditRoute,
  MeActivityTracksTrackIdRoute: MeActivityTracksTrackIdRoute,
  MeActivityTracksUploadRoute: MeActivityTracksUploadRoute,
  AdventuresSlugIndexRoute: AdventuresSlugIndexRoute,
  ClubsClubIdIndexRoute: ClubsClubIdIndexRoute,
  MeActivityTracksIndexRoute: MeActivityTracksIndexRoute,
  AdventuresSlugGroupsGroupIdRoute: AdventuresSlugGroupsGroupIdRoute,
  AdventuresSlugGroupsNewRoute: AdventuresSlugGroupsNewRoute,
  AdventuresSlugHistoryVersionRoute: AdventuresSlugHistoryVersionRoute,
  AdventuresSlugSpotsNewRoute: AdventuresSlugSpotsNewRoute,
  AdventuresSlugTrailsNewRoute: AdventuresSlugTrailsNewRoute,
  AdventuresSlugTripsTripReportIdRoute: AdventuresSlugTripsTripReportIdRoute,
  ClubsClubIdThreadsNewRoute: ClubsClubIdThreadsNewRoute,
  AdventuresSlugGroupsIndexRoute: AdventuresSlugGroupsIndexRoute,
  AdventuresSlugHistoryIndexRoute: AdventuresSlugHistoryIndexRoute,
  ClubsClubIdThreadsThreadIdIndexRoute: ClubsClubIdThreadsThreadIdIndexRoute,
  AdventuresSlugSpotsSpotIdHistoryVersionRoute:
    AdventuresSlugSpotsSpotIdHistoryVersionRoute,
  AdventuresSlugTrailsTrailIdHistoryVersionRoute:
    AdventuresSlugTrailsTrailIdHistoryVersionRoute,
  AdventuresSlugSpotsSpotIdHistoryIndexRoute:
    AdventuresSlugSpotsSpotIdHistoryIndexRoute,
  AdventuresSlugTrailsTrailIdHistoryIndexRoute:
    AdventuresSlugTrailsTrailIdHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
