/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountGuideProfileRouteImport } from './routes/account/guide-profile'
import { Route as AdventuresNewRouteImport } from './routes/adventures/new'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesIdRouteImport } from './routes/guides/$id'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as AdventuresSlugIndexRouteImport } from './routes/adventures/$slug/index'
import { Route as AdventuresSlugEditRouteImport } from './routes/adventures/$slug/edit'
import { Route as AdventuresSlugGroupsIndexRouteImport } from './routes/adventures/$slug/groups/index'
import { Route as AdventuresSlugGroupsGroupIdRouteImport } from './routes/adventures/$slug/groups/$groupId'
import { Route as AdventuresSlugGroupsNewRouteImport } from './routes/adventures/$slug/groups/new'
import { Route as AdventuresSlugHistoryIndexRouteImport } from './routes/adventures/$slug/history/index'
import { Route as AdventuresSlugHistoryVersionRouteImport } from './routes/adventures/$slug/history/$version'
import { Route as AdventuresSlugSpotsNewRouteImport } from './routes/adventures/$slug/spots/new'
import { Route as AdventuresSlugTrailsNewRouteImport } from './routes/adventures/$slug/trails/new'
import { Route as AdventuresSlugTripsTripReportIdRouteImport } from './routes/adventures/$slug/trips/$tripReportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountGuideProfileRoute = AccountGuideProfileRouteImport.update({
  id: '/account/guide-profile',
  path: '/account/guide-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresNewRoute = AdventuresNewRouteImport.update({
  id: '/adventures/new',
  path: '/adventures/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIdRoute = GuidesIdRouteImport.update({
  id: '/guides/$id',
  path: '/guides/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugIndexRoute = AdventuresSlugIndexRouteImport.update({
  id: '/adventures/$slug/',
  path: '/adventures/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugEditRoute = AdventuresSlugEditRouteImport.update({
  id: '/adventures/$slug/edit',
  path: '/adventures/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugGroupsIndexRoute =
  AdventuresSlugGroupsIndexRouteImport.update({
    id: '/adventures/$slug/groups/',
    path: '/adventures/$slug/groups/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugGroupsGroupIdRoute =
  AdventuresSlugGroupsGroupIdRouteImport.update({
    id: '/adventures/$slug/groups/$groupId',
    path: '/adventures/$slug/groups/$groupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugGroupsNewRoute = AdventuresSlugGroupsNewRouteImport.update({
  id: '/adventures/$slug/groups/new',
  path: '/adventures/$slug/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugHistoryIndexRoute =
  AdventuresSlugHistoryIndexRouteImport.update({
    id: '/adventures/$slug/history/',
    path: '/adventures/$slug/history/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugHistoryVersionRoute =
  AdventuresSlugHistoryVersionRouteImport.update({
    id: '/adventures/$slug/history/$version',
    path: '/adventures/$slug/history/$version',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdventuresSlugSpotsNewRoute = AdventuresSlugSpotsNewRouteImport.update({
  id: '/adventures/$slug/spots/new',
  path: '/adventures/$slug/spots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugTrailsNewRoute = AdventuresSlugTrailsNewRouteImport.update({
  id: '/adventures/$slug/trails/new',
  path: '/adventures/$slug/trails/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugTripsTripReportIdRoute =
  AdventuresSlugTripsTripReportIdRouteImport.update({
    id: '/adventures/$slug/trips/$tripReportId',
    path: '/adventures/$slug/trips/$tripReportId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account/guide-profile': typeof AccountGuideProfileRoute
  '/adventures/new': typeof AdventuresNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$id': typeof GuidesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/guides/': typeof GuidesIndexRoute
  '/adventures/$slug/edit': typeof AdventuresSlugEditRoute
  '/adventures/$slug/': typeof AdventuresSlugIndexRoute
  '/adventures/$slug/groups/$groupId': typeof AdventuresSlugGroupsGroupIdRoute
  '/adventures/$slug/groups/new': typeof AdventuresSlugGroupsNewRoute
  '/adventures/$slug/history/$version': typeof AdventuresSlugHistoryVersionRoute
  '/adventures/$slug/spots/new': typeof AdventuresSlugSpotsNewRoute
  '/adventures/$slug/trails/new': typeof AdventuresSlugTrailsNewRoute
  '/adventures/$slug/trips/$tripReportId': typeof AdventuresSlugTripsTripReportIdRoute
  '/adventures/$slug/groups/': typeof AdventuresSlugGroupsIndexRoute
  '/adventures/$slug/history/': typeof AdventuresSlugHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account/guide-profile': typeof AccountGuideProfileRoute
  '/adventures/new': typeof AdventuresNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$id': typeof GuidesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/guides': typeof GuidesIndexRoute
  '/adventures/$slug/edit': typeof AdventuresSlugEditRoute
  '/adventures/$slug': typeof AdventuresSlugIndexRoute
  '/adventures/$slug/groups/$groupId': typeof AdventuresSlugGroupsGroupIdRoute
  '/adventures/$slug/groups/new': typeof AdventuresSlugGroupsNewRoute
  '/adventures/$slug/history/$version': typeof AdventuresSlugHistoryVersionRoute
  '/adventures/$slug/spots/new': typeof AdventuresSlugSpotsNewRoute
  '/adventures/$slug/trails/new': typeof AdventuresSlugTrailsNewRoute
  '/adventures/$slug/trips/$tripReportId': typeof AdventuresSlugTripsTripReportIdRoute
  '/adventures/$slug/groups': typeof AdventuresSlugGroupsIndexRoute
  '/adventures/$slug/history': typeof AdventuresSlugHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account/guide-profile': typeof AccountGuideProfileRoute
  '/adventures/new': typeof AdventuresNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$id': typeof GuidesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/guides/': typeof GuidesIndexRoute
  '/adventures/$slug/edit': typeof AdventuresSlugEditRoute
  '/adventures/$slug/': typeof AdventuresSlugIndexRoute
  '/adventures/$slug/groups/$groupId': typeof AdventuresSlugGroupsGroupIdRoute
  '/adventures/$slug/groups/new': typeof AdventuresSlugGroupsNewRoute
  '/adventures/$slug/history/$version': typeof AdventuresSlugHistoryVersionRoute
  '/adventures/$slug/spots/new': typeof AdventuresSlugSpotsNewRoute
  '/adventures/$slug/trails/new': typeof AdventuresSlugTrailsNewRoute
  '/adventures/$slug/trips/$tripReportId': typeof AdventuresSlugTripsTripReportIdRoute
  '/adventures/$slug/groups/': typeof AdventuresSlugGroupsIndexRoute
  '/adventures/$slug/history/': typeof AdventuresSlugHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account/guide-profile'
    | '/adventures/new'
    | '/auth/callback'
    | '/guides/$id'
    | '/users/$id'
    | '/guides/'
    | '/adventures/$slug/edit'
    | '/adventures/$slug/'
    | '/adventures/$slug/groups/$groupId'
    | '/adventures/$slug/groups/new'
    | '/adventures/$slug/history/$version'
    | '/adventures/$slug/spots/new'
    | '/adventures/$slug/trails/new'
    | '/adventures/$slug/trips/$tripReportId'
    | '/adventures/$slug/groups/'
    | '/adventures/$slug/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account/guide-profile'
    | '/adventures/new'
    | '/auth/callback'
    | '/guides/$id'
    | '/users/$id'
    | '/guides'
    | '/adventures/$slug/edit'
    | '/adventures/$slug'
    | '/adventures/$slug/groups/$groupId'
    | '/adventures/$slug/groups/new'
    | '/adventures/$slug/history/$version'
    | '/adventures/$slug/spots/new'
    | '/adventures/$slug/trails/new'
    | '/adventures/$slug/trips/$tripReportId'
    | '/adventures/$slug/groups'
    | '/adventures/$slug/history'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/account/guide-profile'
    | '/adventures/new'
    | '/auth/callback'
    | '/guides/$id'
    | '/users/$id'
    | '/guides/'
    | '/adventures/$slug/edit'
    | '/adventures/$slug/'
    | '/adventures/$slug/groups/$groupId'
    | '/adventures/$slug/groups/new'
    | '/adventures/$slug/history/$version'
    | '/adventures/$slug/spots/new'
    | '/adventures/$slug/trails/new'
    | '/adventures/$slug/trips/$tripReportId'
    | '/adventures/$slug/groups/'
    | '/adventures/$slug/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AccountGuideProfileRoute: typeof AccountGuideProfileRoute
  AdventuresNewRoute: typeof AdventuresNewRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GuidesIdRoute: typeof GuidesIdRoute
  UsersIdRoute: typeof UsersIdRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  AdventuresSlugEditRoute: typeof AdventuresSlugEditRoute
  AdventuresSlugIndexRoute: typeof AdventuresSlugIndexRoute
  AdventuresSlugGroupsGroupIdRoute: typeof AdventuresSlugGroupsGroupIdRoute
  AdventuresSlugGroupsNewRoute: typeof AdventuresSlugGroupsNewRoute
  AdventuresSlugHistoryVersionRoute: typeof AdventuresSlugHistoryVersionRoute
  AdventuresSlugSpotsNewRoute: typeof AdventuresSlugSpotsNewRoute
  AdventuresSlugTrailsNewRoute: typeof AdventuresSlugTrailsNewRoute
  AdventuresSlugTripsTripReportIdRoute: typeof AdventuresSlugTripsTripReportIdRoute
  AdventuresSlugGroupsIndexRoute: typeof AdventuresSlugGroupsIndexRoute
  AdventuresSlugHistoryIndexRoute: typeof AdventuresSlugHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/guide-profile': {
      id: '/account/guide-profile'
      path: '/account/guide-profile'
      fullPath: '/account/guide-profile'
      preLoaderRoute: typeof AccountGuideProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/new': {
      id: '/adventures/new'
      path: '/adventures/new'
      fullPath: '/adventures/new'
      preLoaderRoute: typeof AdventuresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$id': {
      id: '/guides/$id'
      path: '/guides/$id'
      fullPath: '/guides/$id'
      preLoaderRoute: typeof GuidesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/': {
      id: '/adventures/$slug/'
      path: '/adventures/$slug'
      fullPath: '/adventures/$slug/'
      preLoaderRoute: typeof AdventuresSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/edit': {
      id: '/adventures/$slug/edit'
      path: '/adventures/$slug/edit'
      fullPath: '/adventures/$slug/edit'
      preLoaderRoute: typeof AdventuresSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/groups/': {
      id: '/adventures/$slug/groups/'
      path: '/adventures/$slug/groups'
      fullPath: '/adventures/$slug/groups/'
      preLoaderRoute: typeof AdventuresSlugGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/groups/$groupId': {
      id: '/adventures/$slug/groups/$groupId'
      path: '/adventures/$slug/groups/$groupId'
      fullPath: '/adventures/$slug/groups/$groupId'
      preLoaderRoute: typeof AdventuresSlugGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/groups/new': {
      id: '/adventures/$slug/groups/new'
      path: '/adventures/$slug/groups/new'
      fullPath: '/adventures/$slug/groups/new'
      preLoaderRoute: typeof AdventuresSlugGroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/history/': {
      id: '/adventures/$slug/history/'
      path: '/adventures/$slug/history'
      fullPath: '/adventures/$slug/history/'
      preLoaderRoute: typeof AdventuresSlugHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/history/$version': {
      id: '/adventures/$slug/history/$version'
      path: '/adventures/$slug/history/$version'
      fullPath: '/adventures/$slug/history/$version'
      preLoaderRoute: typeof AdventuresSlugHistoryVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/spots/new': {
      id: '/adventures/$slug/spots/new'
      path: '/adventures/$slug/spots/new'
      fullPath: '/adventures/$slug/spots/new'
      preLoaderRoute: typeof AdventuresSlugSpotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/trails/new': {
      id: '/adventures/$slug/trails/new'
      path: '/adventures/$slug/trails/new'
      fullPath: '/adventures/$slug/trails/new'
      preLoaderRoute: typeof AdventuresSlugTrailsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug/trips/$tripReportId': {
      id: '/adventures/$slug/trips/$tripReportId'
      path: '/adventures/$slug/trips/$tripReportId'
      fullPath: '/adventures/$slug/trips/$tripReportId'
      preLoaderRoute: typeof AdventuresSlugTripsTripReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AccountGuideProfileRoute: AccountGuideProfileRoute,
  AdventuresNewRoute: AdventuresNewRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GuidesIdRoute: GuidesIdRoute,
  UsersIdRoute: UsersIdRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  AdventuresSlugEditRoute: AdventuresSlugEditRoute,
  AdventuresSlugIndexRoute: AdventuresSlugIndexRoute,
  AdventuresSlugGroupsGroupIdRoute: AdventuresSlugGroupsGroupIdRoute,
  AdventuresSlugGroupsNewRoute: AdventuresSlugGroupsNewRoute,
  AdventuresSlugHistoryVersionRoute: AdventuresSlugHistoryVersionRoute,
  AdventuresSlugSpotsNewRoute: AdventuresSlugSpotsNewRoute,
  AdventuresSlugTrailsNewRoute: AdventuresSlugTrailsNewRoute,
  AdventuresSlugTripsTripReportIdRoute: AdventuresSlugTripsTripReportIdRoute,
  AdventuresSlugGroupsIndexRoute: AdventuresSlugGroupsIndexRoute,
  AdventuresSlugHistoryIndexRoute: AdventuresSlugHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
