import type { CurrentUser, MobileLoginResponse, RefreshResponse } from '@adventure/api-types';

import { apiUrl, CLIENT_VERSION, CLIENT_VERSION_HEADER } from '@/lib/api';
import { secureStorage } from './secure-storage';
import { tokenStore } from './token-store';

// Mirrors apps/public/src/lib/auth/session.ts's refresh dedupe, adapted for
// a body-based refresh token instead of a cookie (RN has no shared browser
// cookie jar - MOBILE_PLAN.md Phase 0 item 3). Refresh tokens are
// single-use/rotating (AuthService.refresh() revokes the old row before
// issuing a new pair), so without this, concurrent callers on cold start
// would race the same stored token and all but one would 401.
let inFlightRefresh: Promise<boolean> | null = null;

async function performRefresh(refreshToken: string): Promise<boolean> {
  try {
    const res = await fetch(apiUrl('/auth/refresh'), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', [CLIENT_VERSION_HEADER]: CLIENT_VERSION },
      body: JSON.stringify({ refreshToken }),
    });
    if (!res.ok) {
      return false;
    }
    const data: RefreshResponse = await res.json();
    tokenStore.set(data.accessToken);
    await secureStorage.setRefreshToken(data.refreshToken);
    return true;
  } catch {
    return false;
  }
}

// Cold-start check: mints a fresh access token from the stored refresh
// token. Call once on app launch before rendering anything auth-gated.
export async function restoreSession(): Promise<boolean> {
  if (tokenStore.get()) {
    return true;
  }
  if (inFlightRefresh) {
    return inFlightRefresh;
  }
  const stored = await secureStorage.getRefreshToken();
  if (!stored) {
    return false;
  }
  inFlightRefresh = performRefresh(stored).finally(() => {
    inFlightRefresh = null;
  });
  return inFlightRefresh;
}

export async function completeGoogleMobileLogin(idToken: string): Promise<CurrentUser> {
  const res = await fetch(apiUrl('/auth/google/mobile'), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', [CLIENT_VERSION_HEADER]: CLIENT_VERSION },
    body: JSON.stringify({ idToken }),
  });
  if (!res.ok) {
    const message = await res.text().catch(() => res.statusText);
    throw new Error(message || `Login failed: ${res.status}`);
  }
  const data: MobileLoginResponse = await res.json();
  tokenStore.set(data.accessToken);
  await secureStorage.setRefreshToken(data.refreshToken);
  return {
    userId: data.user.id,
    email: data.user.email,
    username: data.user.username,
    usernameIsAutoGenerated: data.user.usernameIsAutoGenerated,
    role: data.user.role,
  };
}

export async function fetchCurrentUser(): Promise<CurrentUser | null> {
  const authenticated = tokenStore.get() ? true : await restoreSession();
  if (!authenticated) {
    return null;
  }
  const res = await fetch(apiUrl('/auth/me'), {
    headers: { Authorization: `Bearer ${tokenStore.get()}` },
  });
  if (!res.ok) {
    return null;
  }
  return res.json();
}

export async function logout(): Promise<void> {
  const refreshToken = await secureStorage.getRefreshToken();
  await fetch(apiUrl('/auth/logout'), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ refreshToken }),
  }).catch(() => undefined);
  tokenStore.set(null);
  await secureStorage.clearRefreshToken();
}
